# This is a basic workflow to help you get started with Actions

name: Automated build and unit tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        hdf5: [true]
        compiler: [clang]
        include:
          - compiler: gcc
            cc: gcc
            cpp: g++
          - compiler: clang
            cc: clang
            cpp: clang++

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      if: matrix.hdf5
      run: |
        sudo apt install libhdf5-dev

    # Runs a single command using the runners shell
    - name: Configure
      run: |
        cd $GITHUB_WORKSPACE
        mkdir build
        cd build
        which ${{ matrix.cc }}
        which ${{ matrix.cpp }}
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp }} ..
        
    - name: Compile
      run: |
        cd $GITHUB_WORKSPACE
        cd build
        make -j4
    
    - name: Compile unit tests
      run: |
        cd $GITHUB_WORKSPACE
        cd build
        make buildTests -j4
    
    - name: Run unit tests
      if: matrix.hdf5
      run: |
        cd $GITHUB_WORKSPACE
        cd build
        make check -j4
